// lib/metadata.mjs
// Capa EDITORIAL (curada a mano). Los datos mecanicos (precios, limites,
// peticiones, privacidad, endpoints) se actualizan solos desde la doc.
// Aca viven la calidad relativa, el contexto, los casos de uso y el esfuerzo.
//
// `quality` es un ranking relativo 1-10 (juicio propio, no benchmark oficial).
// `volumeRank` ordena preferencia para trabajo de ALTO VOLUMEN (6000+ req/5h).
// Si aparece un modelo nuevo sin ficha, el sistema lo marca como "sin ficha".

export const EDITORIAL = {
  'GLM-5.3-Flash': {
    lab: 'Zhipu (Z.ai)', kind: 'Rapido, multimodal nativo, agentico',
    context: 1000000, tags: ['frontend', 'vision', 'multimodal', 'agentic', 'fast', 'high-volume', 'computer-use'],
    bestFor: ['Frontend/UI desde capturas o render', 'Desarrollo de juegos y escenas 3D', 'Agentes baratos con vision integrada'],
    strengths: 'El mas eficiente en costo/rendimiento de la familia GLM-5; vision integrada en el loop de coding.',
    effort: { modes: 'low / high / max', default: 'max', recommend: 'max para coding; low para tareas simples' },
    role: 'default', quality: 8.5, speed: 'alto', volumeRank: 3,
    confidence: 'alta',
  },
  'GLM-5.3': {
    lab: 'Zhipu (Z.ai)', kind: 'Flagship text-only, razonamiento agentico',
    context: 1000000, tags: ['refactor', 'multi-file', 'systems', 'debug', 'security', 'reasoning', 'long-horizon', 'long-context'],
    bestFor: ['Refactors grandes y multiarchivo', 'Ingenieria de sistemas y debugging profundo', 'Seguridad y descubrimiento de vulnerabilidades'],
    strengths: 'El open-weights mas fuerte para coding y ciberseguridad; tareas de varios dias de ingenieria.',
    effort: { modes: 'low / high / max', default: 'max', recommend: 'high diario; max en seguridad y razonamiento duro' },
    role: 'escalado', quality: 9.3, speed: 'medio',
    confidence: 'alta',
  },
  'GLM-5.2': {
    lab: 'Zhipu (Z.ai)', kind: 'Flagship long-context, generacion previa',
    context: 1000000, tags: ['refactor', 'multi-file', 'long-context', 'systems'],
    bestFor: ['Auditoria de codebase completo (1M)', 'Migraciones de API/SDK', 'Desarrollo movil'],
    strengths: 'Contexto 1M "lossless"; admite desactivar el thinking.',
    effort: { modes: 'low / high / max (o thinking off)', default: 'max', recommend: 'high; desactivar thinking en tareas triviales' },
    role: 'respaldo', quality: 7.8, speed: 'medio',
    confidence: 'alta',
  },
  'Kimi K3': {
    lab: 'Moonshot', kind: 'Frontera agentico + multimodal (imagen/video)',
    context: 1000000, tags: ['refactor', 'multi-file', 'agentic', 'long-horizon', 'long-context', 'vision', 'multimodal', 'research', 'systems'],
    bestFor: ['Repos masivos con minima supervision', 'Kernels GPU, compiladores, CAD', 'Research y trabajo agentico de largo aliento'],
    strengths: 'Frontera para sesiones de ingenieria largas; multimodal y 1M de contexto.',
    effort: { modes: 'low / high / max', default: 'max', recommend: 'high diario; max en lo mas dificil' },
    role: 'escalado', quality: 9.5, speed: 'medio',
    confidence: 'alta',
  },
  'Kimi K2.7 Code': {
    lab: 'Moonshot', kind: 'Coding agentico especializado, multimodal',
    context: 256000, tags: ['refactor', 'multi-file', 'debug', 'agentic', 'code-daily', 'vision'],
    bestFor: ['Edicion multiarchivo', 'Features grandes', 'Debugging de sesiones largas'],
    strengths: 'Especializado en codigo; reduce el "overthinking" (~30% menos thinking tokens).',
    effort: { modes: 'thinking forzado (sin niveles)', default: 'on', recommend: 'siempre razona; no configurable' },
    role: 'default', quality: 8.4, speed: 'alto',
    confidence: 'alta',
  },
  'Kimi K2.6': {
    lab: 'Moonshot', kind: 'Agentico multimodal, generacion previa',
    context: 256000, tags: ['agentic', 'multi-file', 'vision', 'frontend'],
    bestFor: ['Orquestacion multi-agente', 'Diseno/coding desde referencias visuales'],
    strengths: 'Hibrido Thinking/Instant; fuerte en agent swarm.',
    effort: { modes: 'Thinking (on) / Instant (off)', default: 'on', recommend: 'on para codigo; Instant para respuestas rapidas' },
    role: 'respaldo', quality: 7.5, speed: 'alto',
    confidence: 'alta',
  },
  'LongCat-2.0': {
    lab: 'Meituan', kind: 'Agentico repo-level, texto, muy barato',
    context: 1000000, tags: ['refactor', 'multi-file', 'long-context', 'agentic', 'cheap', 'high-volume'],
    bestFor: ['Refactors repo-level', 'Entendimiento de repos grandes', 'Volumen alto a bajo costo'],
    strengths: 'MoE 1.6T, 1M de contexto, open MIT, muy barato.',
    effort: { modes: 'enable_thinking on/off', default: 'on', recommend: 'on para codigo' },
    role: 'respaldo', quality: 7.6, speed: 'alto', volumeRank: 5,
    confidence: 'alta',
  },
  'LongCat 2.5 Preview Free': {
    lab: 'Meituan', kind: 'Multimodal + agentico (preview, gratis)',
    context: 1000000, tags: ['vision', 'multimodal', 'long-context', 'cheap', 'prototyping'],
    bestFor: ['Experimentacion gratuita', 'Leer capturas + codigo'],
    strengths: '1M de contexto y entrada de imagen, sin costo por tiempo limitado.',
    effort: { modes: 'razonamiento (sin niveles documentados)', default: 'on', recommend: 'usar tal cual' },
    role: 'banco de pruebas', quality: 7.0, speed: 'medio', volumeRank: 8, free: true,
    caution: 'Preview sin benchmarks oficiales; no usar como motor critico.',
    confidence: 'baja',
  },
  'Step 5 Preview Free': {
    lab: 'StepFun', kind: 'Razonador multimodal, SWE y finanzas (gratis)',
    context: 1000000, tags: ['refactor', 'research', 'vision', 'multimodal', 'long-context', 'cheap'],
    bestFor: ['Codebases grandes', 'Analisis financiero/documental', 'Multimodal (charts, screenshots, video)'],
    strengths: '1M de contexto, multimodal nativo, gratis por tiempo limitado.',
    effort: { modes: 'low / medium / high', default: 'medium', recommend: 'high para coding (es verboso)' },
    role: 'default gratis', quality: 8.2, speed: 'medio', volumeRank: 7, free: true,
    caution: 'Preview; flojo en Terminal-Bench; verboso con esfuerzo alto.',
    confidence: 'media',
  },
  'MiMo-V2.6-Flash': {
    lab: 'Xiaomi', kind: 'Omnimodal + agentico eficiente',
    context: 1000000, tags: ['vision', 'multimodal', 'audio', 'agentic', 'high-volume', 'code-daily', 'fast', 'computer-use'],
    bestFor: ['Uso intensivo diario', 'Visual coding', 'Agentes con muchas herramientas'],
    strengths: 'Omnimodal (texto/imagen/video/audio), 1M, gran relacion precio/capacidad.',
    effort: { modes: 'thinking toggle (niveles no verificados)', default: 'on', recommend: 'on para codigo' },
    role: 'default', quality: 8.6, speed: 'alto', volumeRank: 2,
    confidence: 'alta',
  },
  'MiMo-V2.6-Pro': {
    lab: 'Xiaomi', kind: 'Flagship agentico omnimodal',
    context: 1000000, tags: ['refactor', 'multi-file', 'debug', 'security', 'agentic', 'long-horizon', 'vision', 'multimodal'],
    bestFor: ['Refactors dificiles', 'Debugging complejo', 'Seguridad'],
    strengths: 'El MiMo mas capaz; omnimodal y 1M de contexto.',
    effort: { modes: 'thinking toggle (niveles no verificados)', default: 'on', recommend: 'on para tareas exigentes' },
    role: 'escalado', quality: 9.0, speed: 'medio',
    confidence: 'alta',
  },
  'MiMo-V2.5': {
    lab: 'Xiaomi', kind: 'Agentico eficiente, generacion previa',
    context: 1000000, tags: ['fast', 'cheap', 'high-volume', 'code-daily', 'agentic'],
    bestFor: ['Autocompletado / codigo rapido', 'Agentes economicos'],
    strengths: 'Eficiente y barato; superado por V2.6.',
    effort: { modes: 'thinking on/off', default: 'off', recommend: 'on para codigo' },
    role: 'respaldo', quality: 7.0, speed: 'alto', volumeRank: 6,
    confidence: 'media',
  },
  'MiMo-V2.5-Pro': {
    lab: 'Xiaomi', kind: 'Agentico long-horizon texto, 1T',
    context: 1000000, tags: ['refactor', 'multi-file', 'systems', 'long-horizon', 'long-context'],
    bestFor: ['Proyectos end-to-end largos', 'Compiladores/backends', 'Ingenieria profunda'],
    strengths: 'Sostiene >1000 llamadas de herramienta; 1M de contexto.',
    effort: { modes: 'thinking on/off', default: 'on', recommend: 'on para ingenieria profunda' },
    role: 'respaldo', quality: 7.5, speed: 'medio',
    confidence: 'alta',
  },
  'MiniMax M3': {
    lab: 'MiniMax', kind: 'Frontera coding + multimodal + computer-use',
    context: 1000000, tags: ['refactor', 'multi-file', 'debug', 'agentic', 'long-horizon', 'vision', 'multimodal', 'computer-use', 'gui', 'high-volume'],
    bestFor: ['Refactors y debugging', 'Agentes largos autonomos', 'Tareas multimodal/computer-use'],
    strengths: 'Atencion sparse; ejecuciones autonomas larguisimas; muy buena generalizacion de scaffolds.',
    effort: { modes: 'thinking on/off por request', default: 'on', recommend: 'on para complejo/agentico; off para baja latencia' },
    role: 'default', quality: 8.8, speed: 'medio',
    confidence: 'alta',
  },
  'MiniMax M2.7': {
    lab: 'MiniMax', kind: 'Agentico texto, ofimatica y debugging',
    context: 200000, tags: ['debug', 'office', 'agentic', 'refactor', 'code-daily'],
    bestFor: ['Logs y bug hunting', 'Refactors', 'Excel/PPT/Word'],
    strengths: 'Fuerte en ingenieria real y ofimatica; Agent Teams nativos.',
    effort: { modes: 'modelo razonador (niveles no verificados)', default: 'on', recommend: 'on para debugging' },
    role: 'respaldo', quality: 7.6, speed: 'alto',
    confidence: 'alta',
  },
  'Muse Spark 1.3 Contributor': {
    lab: 'Meta', kind: 'Agentico/coding multimodal (Contributor)',
    context: 1000000, tags: ['agentic', 'multi-file', 'long-horizon', 'vision', 'multimodal', 'research', 'high-volume'],
    bestFor: ['Tareas agenticas largas', 'Leer documentos/video/PDF', 'Coding con herramientas'],
    strengths: '1M de contexto, tool-calling paralelo con streaming, reasoning replay.',
    effort: { modes: 'minimal / low / medium / high / xhigh (max solo Standard)', default: 'medium', recommend: 'high/xhigh para codigo complejo' },
    role: 'default (solo codigo no sensible)', quality: 8.4, speed: 'medio', volumeRank: 9, trainsData: true,
    caution: 'Meta entrena con tus prompts y respuestas. Sin ZDR. No usar con codigo propietario.',
    confidence: 'alta',
  },
  'Muse Spark 1.2 Contributor': {
    lab: 'Meta', kind: 'Agentico/coding multimodal con audio (Contributor)',
    context: 1000000, tags: ['agentic', 'vision', 'multimodal', 'audio', 'high-volume'],
    bestFor: ['Tareas con audio', 'Respaldo de 1.3'],
    strengths: 'Igual que 1.3 y ademas soporta audio.',
    effort: { modes: 'minimal / low / medium / high / xhigh (max solo Standard)', default: 'medium', recommend: 'high/xhigh para codigo complejo' },
    role: 'respaldo (solo codigo no sensible)', quality: 8.0, speed: 'medio', volumeRank: 10, trainsData: true,
    caution: 'Meta entrena con tus prompts y respuestas. Sin ZDR. No usar con codigo propietario.',
    confidence: 'alta',
  },
  'Qwen3.8 Max': {
    lab: 'Alibaba', kind: 'Flagship multimodal, largo horizonte',
    context: 1000000, tags: ['refactor', 'agentic', 'long-horizon', 'vision', 'multimodal', 'frontend', 'reasoning'],
    bestFor: ['Proyectos de escala ingenieril', 'Desarrollo autonomo largo', 'Frontend desde screenshot'],
    strengths: 'MoE 2.4T (95B activos); razonamiento visual y planificacion autonoma.',
    effort: { modes: 'enable_thinking + presupuesto (sin niveles low/high/max)', default: 'on', recommend: 'presupuesto alto para planificacion' },
    role: 'escalado', quality: 9.2, speed: 'medio',
    confidence: 'alta',
  },
  'Qwen3.8 Flash': {
    lab: 'Alibaba', kind: 'Multimodal barato de alto rendimiento',
    context: 1000000, tags: ['fast', 'cheap', 'high-volume', 'code-daily', 'vision', 'multimodal', 'frontend'],
    bestFor: ['Iteracion/implementacion rutinaria', 'Edicion multiarchivo', 'Charts y video'],
    strengths: 'Excelente benchmark/dolar; 1M; supera a modelos mayores con 6B activos.',
    effort: { modes: 'enable_thinking on/off', default: 'on', recommend: 'on para codigo; off para rutina' },
    role: 'default', quality: 8.2, speed: 'alto', volumeRank: 11,
    caution: 'Revisar seguridad/confiabilidad (trackers independientes mas moderados).',
    confidence: 'media',
  },
  'Qwen3.7 Plus': {
    lab: 'Alibaba', kind: 'Agente multimodal GUI+CLI, OCR lider',
    context: 1000000, tags: ['vision', 'multimodal', 'gui', 'computer-use', 'code-daily', 'agentic', 'long-context', 'docs'],
    bestFor: ['Agentes GUI/navegacion', 'OCR/documentos', 'Coding asistido por vision'],
    strengths: 'Lider en OCRBench_V2; unifica operacion GUI y CLI; 1M.',
    effort: { modes: 'enable_thinking + presupuesto', default: 'on', recommend: 'on para GUI/vision' },
    role: 'default con vision', quality: 8.0, speed: 'alto',
    confidence: 'alta',
  },
  'DeepSeek V4.1 Flash': {
    lab: 'DeepSeek', kind: 'Agentico multimodal nativo, alto throughput',
    context: 1000000, tags: ['agentic', 'multi-file', 'high-volume', 'vision', 'multimodal', 'fast', 'code-daily', 'refactor'],
    bestFor: ['Loops agenticos de alto volumen', 'Edicion multiarchivo', 'Entrada de imagenes (docs/UI/screenshots)'],
    strengths: 'Por delante de V4-Pro en coding agentico; multimodal y muy barato; 1M.',
    effort: { modes: 'thinking on/off (niveles estimados)', default: 'on', recommend: 'on para agentico' },
    role: 'default', quality: 9.0, speed: 'alto', volumeRank: 1,
    confidence: 'alta',
  },
  'DeepSeek V4 Pro': {
    lab: 'DeepSeek', kind: 'Flagship razonador texto (en retirada)',
    context: 1000000, tags: ['refactor', 'math', 'reasoning', 'debug', 'systems', 'multi-file'],
    bestFor: ['Refactors grandes', 'Matematica dura', 'Debugging profundo'],
    strengths: 'Razonamiento/matematica de frontera; 1M; text-only.',
    effort: { modes: 'low / high / max', default: 'high', recommend: 'high agente diario; max complejo' },
    role: 'escalado', quality: 8.8, speed: 'medio',
    caution: 'En retirada: el endpoint rutea a V4.1 Flash.',
    confidence: 'alta',
  },
  'DeepSeek V4 Flash': {
    lab: 'DeepSeek', kind: 'Rapido/barato, 1M contexto (retirado)',
    context: 1000000, tags: ['fast', 'cheap', 'high-volume', 'code-daily', 'agentic'],
    bestFor: ['Edicion rapida', 'Agentes ligeros', 'Presupuesto ajustado'],
    strengths: 'Muy barato y rapido; 1M.',
    effort: { modes: 'low / high / max', default: 'high', recommend: 'high uso general' },
    role: 'respaldo/legacy', quality: 7.6, speed: 'alto', volumeRank: 4,
    caution: 'Retirado de la API oficial; hoy conviene V4.1 Flash.',
    confidence: 'alta',
  },
  'DeepSeek V4 Flash Vision Exp': {
    lab: 'DeepSeek', kind: 'Experimental con vision (retirado)',
    context: 1000000, tags: ['vision', 'multimodal', 'agentic', 'high-volume'],
    bestFor: ['Vision dentro de agentes (screenshots, charts, UI)'],
    strengths: 'Lleva el rendimiento agentico multimodal cerca de Opus-4.8.',
    effort: { modes: 'thinking on/off (niveles estimados)', default: 'on', recommend: 'on para vision' },
    role: 'respaldo nicho', quality: 7.2, speed: 'alto', volumeRank: 6,
    caution: 'Experimental y retirado; sin benchmarks de documentos publicados.',
    confidence: 'media',
  },
  'Hy4 preview': {
    lab: 'Tencent', kind: 'Flagship agentico/razonador, front-end fuerte',
    context: 1000000, tags: ['refactor', 'debug', 'frontend', 'agentic', 'long-horizon', 'long-context', 'reasoning', 'math'],
    bestFor: ['Agentes largos dificiles', 'Debugging/verificacion', 'Front-end'],
    strengths: 'Lider open-source de su generacion; supero levemente a GLM 5.3 y Kimi K3 en eval ciega interna.',
    effort: { modes: 'high (default) / no_think', default: 'high', recommend: 'high en codigo/math; no_think en consultas directas' },
    role: 'escalado/fuerza', quality: 9.2, speed: 'bajo',
    caution: 'Razona y se auto-verifica de mas: lento y verboso en tareas simples.',
    confidence: 'alta',
  },
  'Hy3': {
    lab: 'Tencent', kind: 'Razonador/agente coste-eficiente',
    context: 256000, tags: ['code-daily', 'frontend', 'agentic', 'cheap', 'stabilization'],
    bestFor: ['Codigo diario', 'Front-end', 'Data/storage, CI-CD'],
    strengths: 'Coste-eficiencia y estabilidad entre scaffolds; anti-alucinacion.',
    effort: { modes: 'no_think (default) / low / high', default: 'no_think', recommend: 'high en codigo/math' },
    role: 'default barato', quality: 8.0, speed: 'alto',
    caution: 'Contexto de 256K: fuera de tareas de contexto masivo.',
    confidence: 'alta',
  },
  'Space Bunny': {
    lab: 'Desconocido', kind: 'Razonador multimodal largo, revision de codigo',
    context: 1000000, tags: ['research', 'long-context', 'vision', 'multimodal', 'docs', 'debug'],
    bestFor: ['Revision de repos largos', 'Analisis de incidentes', 'Screenshots (lento)'],
    strengths: '1M de contexto, 5 niveles de esfuerzo, encuentra stubs que otros pasan por alto.',
    effort: { modes: 'low / medium / high / xhigh / max', default: 'low', recommend: 'medium/high para revision; fijar explícito' },
    role: 'experimental', quality: 7.0, speed: 'bajo',
    caution: 'Procedencia anonima, sin benchmarks oficiales, muy lento.',
    confidence: 'baja',
  },
  'Grok 4.7': {
    lab: 'xAI', kind: 'Frontera coding + knowledge work, auto-verifica',
    context: 500000, tags: ['refactor', 'multi-file', 'agentic', 'long-horizon', 'reasoning', 'research'],
    bestFor: ['Refactors grandes', 'Agentes multi-hora', 'Tareas legales/EE'],
    strengths: 'Trabaja mas tiempo en tareas dificiles y se auto-verifica.',
    effort: { modes: 'low / medium / high (default) / xhigh', default: 'high', recommend: 'high diario; xhigh lo mas dificil' },
    role: 'escalado', quality: 8.7, speed: 'medio',
    confidence: 'alta',
  },
  'Grok 4.6': {
    lab: 'xAI', kind: 'Frontera coding/agentes, generacion previa',
    context: 500000, tags: ['prototyping', 'frontend', 'agentic', 'multi-file'],
    bestFor: ['Prototipado interactivo/visual', 'Agentes'],
    strengths: 'Sostiene tareas de muchos pasos; fuerte "de idea a app".',
    effort: { modes: 'low / medium / high (default) / xhigh', default: 'high', recommend: 'high' },
    role: 'respaldo', quality: 7.8, speed: 'medio',
    caution: 'Inferior a 4.7 al mismo precio.',
    confidence: 'media',
  },
  'GPT 6 Luna': {
    lab: 'OpenAI', kind: 'Rapido/economico con razonamiento ajustable',
    context: 1050000, tags: ['fast', 'cheap', 'high-volume', 'code-daily', 'agentic', 'multimodal', 'docs'],
    bestFor: ['Alto volumen y subagentes', 'Compaction/resumenes', 'Coding rapido'],
    strengths: 'Excelente costo-inteligencia; contexto enorme; muy usado.',
    effort: { modes: 'none / low / medium (default) / high / xhigh / max', default: 'medium', recommend: 'medium rapido; high multiarchivo; max SWE' },
    role: 'default economico', quality: 8.0, speed: 'alto',
    confidence: 'media',
  },
  'GPT 5.6 Luna': {
    lab: 'OpenAI', kind: 'Rapido/economico, generacion previa',
    context: 1000000, tags: ['fast', 'cheap', 'code-daily', 'multimodal'],
    bestFor: ['Compatibilidad/respaldo', 'Coding estandar'],
    strengths: 'Resultados solidos, pero 2x mas caro que GPT 6 Luna.',
    effort: { modes: 'esquema GPT-5.6 (... / high / xhigh / max)', default: 'high', recommend: 'high' },
    role: 'respaldo', quality: 7.6, speed: 'alto',
    caution: 'Superado por GPT 6 Luna en precio.',
    confidence: 'media',
  },
  'Claude Haiku 5.5': {
    lab: 'Anthropic', kind: 'El mas rapido de Anthropic, computer-use',
    context: 1000000, tags: ['fast', 'cheap', 'high-volume', 'computer-use', 'gui', 'vision', 'docs'],
    bestFor: ['Summaries y compaction', 'Clasificacion', 'Subagente de coding'],
    strengths: 'Rapido, razonamiento visual y computer-use fuertes; 1M.',
    effort: { modes: 'effort low -> max (adaptable)', default: 'medium', recommend: 'low/medium alto volumen; high/xhigh subagente' },
    role: 'subagente', quality: 7.4, speed: 'muy alto',
    caution: 'No es la mejor opcion para coding agentico complejo.',
    confidence: 'media',
  },
};

// Variantes REALES que expone OpenCode por id de modelo (provider opencode-go).
// Capturadas del runtime de OpenCode. Si un id no figura, se asume [] (sin variant).
// refresh.mjs no puede leer el runtime, por eso vive aca; la skill verifica en vivo.
export const VARIANTS = {
  'claude-haiku-5-5': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
  'space-bunny': ['low', 'medium', 'high', 'xhigh', 'max'],
  'gpt-6-luna': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
  'grok-4.7': ['low', 'medium', 'high', 'xhigh'],
  'step-5-preview-free': ['low', 'medium', 'high'],
  'deepseek-v4.1-flash': ['low', 'high', 'max'],
  'muse-spark-1.3-contributor': ['minimal', 'low', 'medium', 'high', 'xhigh'],
  'hy4-preview': ['none', 'high'],
  'glm-5.3-flash': ['low', 'high', 'max'],
  'qwen3.8-flash': ['none', 'low', 'medium', 'xhigh'],
  'glm-5.3': ['low', 'high', 'max'],
  'qwen3.8-max': ['none', 'low', 'medium', 'xhigh'],
  'kimi-k3': ['max'],
  'qwen3.7-plus': ['none', 'high', 'max'],
  'minimax-m3': ['none', 'thinking'],
  'deepseek-v4-pro': ['high', 'max'],
};

/** Orden curado para el set de alto volumen (6000+ req/5h en Go). */
export const HIGH_VOLUME_ORDER = [
  'DeepSeek V4.1 Flash',
  'MiMo-V2.6-Flash',
  'GLM-5.3-Flash',
  'DeepSeek V4 Flash',
  'LongCat-2.0',
  'DeepSeek V4 Flash Vision Exp',
  'MiMo-V2.5',
  'Step 5 Preview Free',
  'LongCat 2.5 Preview Free',
  'Muse Spark 1.3 Contributor',
  'Muse Spark 1.2 Contributor',
];

export const LABELS = {
  quality: 'Calidad relativa (1-10, editorial)',
};
